SELECT * FROM pays;

INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (4,'AFGHANISTAN','AFG','AF');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (8,'ALBANIE','ALB','AL');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (10,'ANTARCTIQUE','ATA','AQ');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (12,'ALGÉRIE','DZA','DZ');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (16,'SAMOA AMÉRICAINES','ASM','AS');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (20,'ANDORRE','AND','AD');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (24,'ANGOLA','AGO','AO');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (28,'ANTIGUA-ET-BARBUDA','ATG','AG');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (31,'AZERBAÏDJAN','AZE','AZ');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (32,'ARGENTINE','ARG','AR');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (36,'AUSTRALIE','AUS','AU');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (40,'AUTRICHE','AUT','AT');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (44,'BAHAMAS','BHS','BS');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (48,'BAHREÏN','BHR','BH');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (50,'BANGLADESH','BGD','BD');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (51,'ARMÉNIE','ARM','AM');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (52,'BARBADE','BRB','BB');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (56,'BELGIQUE','BEL','BE');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (60,'BERMUDES','BMU','BM');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (64,'BHOUTAN','BTN','BT');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (68,'BOLIVIE, ÉTAT PLURINATIONAL DE','BOL','BO');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (70,'BOSNIE-HERZÉGOVINE','BIH','BA');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (72,'BOTSWANA','BWA','BW');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (74,'BOUVET, ÎLE','BVT','BV');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (76,'BRÉSIL','BRA','BR');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (84,'BELIZE','BLZ','BZ');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (86,'OCÉAN INDIEN, TERRITOIRE BRITANNIQUE DE L''','IOT','IO');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (90,'SALOMON, ÎLES','SLB','SB');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (92,'ÎLES VIERGES BRITANNIQUES','VGB','VG');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (96,'BRUNÉI DARUSSALAM','BRN','BN');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (100,'BULGARIE','BGR','BG');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (104,'MYANMAR','MMR','MM');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (108,'BURUNDI','BDI','BI');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (112,'BÉLARUS','BLR','BY');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (116,'CAMBODGE','KHM','KH');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (120,'CAMEROUN','CMR','CM');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (124,'CANADA','CAN','CA');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (132,'CABO VERDE','CPV','CV');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (136,'CAÏMANES, ÎLES','CYM','KY');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (140,'CENTRAFRICAINE, RÉPUBLIQUE','CAF','CF');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (144,'SRI LANKA','LKA','LK');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (148,'TCHAD','TCD','TD');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (152,'CHILI','CHL','CL');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (156,'CHINE','CHN','CN');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (158,'TAÏWAN, PROVINCE DE CHINE','TWN','TW');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (162,'CHRISTMAS, ÎLE','CXR','CX');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (166,'COCOS (KEELING), ÎLES','CCK','CC');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (170,'COLOMBIE','COL','CO');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (174,'COMORES','COM','KM');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (175,'MAYOTTE','MYT','YT');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (178,'CONGO','COG','CG');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (180,'CONGO, LA RÉPUBLIQUE DÉMOCRATIQUE DU','COD','CD');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (184,'COOK, ÎLES','COK','CK');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (188,'COSTA RICA','CRI','CR');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (191,'CROATIE','HRV','HR');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (192,'CUBA','CUB','CU');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (196,'CHYPRE','CYP','CY');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (203,'TCHÉQUIE','CZE','CZ');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (204,'BÉNIN','BEN','BJ');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (208,'DANEMARK','DNK','DK');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (212,'DOMINIQUE','DMA','DM');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (214,'DOMINICAINE, RÉPUBLIQUE','DOM','DO');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (218,'ÉQUATEUR','ECU','EC');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (222,'EL SALVADOR','SLV','SV');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (226,'GUINÉE ÉQUATORIALE','GNQ','GQ');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (231,'ÉTHIOPIE','ETH','ET');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (232,'ÉRYTHRÉE','ERI','ER');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (233,'ESTONIE','EST','EE');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (234,'FÉROÉ, ÎLES','FRO','FO');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (238,'FALKLAND, ÎLES (MALVINAS)','FLK','FK');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (239,'GÉORGIE DU SUD ET LES ÎLES SANDWICH DU SUD','SGS','GS');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (242,'FIDJI','FJI','FJ');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (246,'FINLANDE','FIN','FI');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (248,'ÅLAND, ÎLES','ALA','AX');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (250,'FRANCE','FRA','FR');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (254,'GUYANE FRANÇAISE','GUF','GF');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (258,'POLYNÉSIE FRANÇAISE','PYF','PF');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (260,'TERRES AUSTRALES FRANÇAISES','ATF','TF');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (262,'DJIBOUTI','DJI','DJ');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (266,'GABON','GAB','GA');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (268,'GÉORGIE','GEO','GE');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (270,'GAMBIE','GMB','GM');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (275,'ÉTAT DE PALESTINE','PSE','PS');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (276,'ALLEMAGNE','DEU','DE');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (288,'GHANA','GHA','GH');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (292,'GIBRALTAR','GIB','GI');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (296,'KIRIBATI','KIR','KI');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (300,'GRÈCE','GRC','GR');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (304,'GROENLAND','GRL','GL');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (308,'GRENADE','GRD','GD');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (312,'GUADELOUPE','GLP','GP');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (316,'GUAM','GUM','GU');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (320,'GUATEMALA','GTM','GT');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (324,'GUINÉE','GIN','GN');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (328,'GUYANA','GUY','GY');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (332,'HAÏTI','HTI','HT');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (334,'HEARD ET MACDONALD, ÎLES','HMD','HM');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (336,'SAINT-SIÈGE (ÉTAT DE LA CITÉ DU VATICAN)','VAT','VA');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (340,'HONDURAS','HND','HN');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (344,'HONG KONG','HKG','HK');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (348,'HONGRIE','HUN','HU');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (352,'ISLANDE','ISL','IS');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (356,'INDE','IND','IN');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (360,'INDONÉSIE','IDN','ID');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (364,'IRAN, RÉPUBLIQUE ISLAMIQUE D''','IRN','IR');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (368,'IRAQ','IRQ','IQ');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (372,'IRLANDE','IRL','IE');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (376,'ISRAËL','ISR','IL');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (380,'ITALIE','ITA','IT');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (384,'CÔTE D’IVOIRE','CIV','CI');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (388,'JAMAÏQUE','JAM','JM');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (392,'JAPON','JPN','JP');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (398,'KAZAKHSTAN','KAZ','KZ');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (400,'JORDANIE','JOR','JO');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (404,'KENYA','KEN','KE');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (408,'CORÉE, RÉPUBLIQUE POPULAIRE DÉMOCRATIQUE DE','PRK','KP');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (410,'CORÉE, RÉPUBLIQUE DE','KOR','KR');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (414,'KOWEÏT','KWT','KW');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (417,'KIRGHIZISTAN','KGZ','KG');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (418,'LAO, RÉPUBLIQUE DÉMOCRATIQUE POPULAIRE','LAO','LA');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (422,'LIBAN','LBN','LB');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (426,'LESOTHO','LSO','LS');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (428,'LETTONIE','LVA','LV');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (430,'LIBÉRIA','LBR','LR');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (434,'LIBYE','LBY','LY');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (438,'LIECHTENSTEIN','LIE','LI');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (440,'LITUANIE','LTU','LT');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (442,'LUXEMBOURG','LUX','LU');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (446,'MACAO','MAC','MO');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (450,'MADAGASCAR','MDG','MG');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (454,'MALAWI','MWI','MW');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (458,'MALAISIE','MYS','MY');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (462,'MALDIVES','MDV','MV');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (466,'MALI','MLI','ML');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (470,'MALTE','MLT','MT');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (474,'MARTINIQUE','MTQ','MQ');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (478,'MAURITANIE','MRT','MR');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (480,'MAURICE','MUS','MU');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (484,'MEXIQUE','MEX','MX');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (492,'MONACO','MCO','MC');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (496,'MONGOLIE','MNG','MN');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (498,'MOLDAVIE','MDA','MD');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (499,'MONTÉNÉGRO','MNE','ME');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (500,'MONTSERRAT','MSR','MS');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (504,'MAROC','MAR','MA');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (508,'MOZAMBIQUE','MOZ','MZ');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (512,'OMAN','OMN','OM');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (516,'NAMIBIE','NAM','NA');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (520,'NAURU','NRU','NR');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (524,'NÉPAL','NPL','NP');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (528,'PAYS-BAS','NLD','NL');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (531,'CURAÇAO','CUW','CW');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (533,'ARUBA','ABW','AW');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (534,'SAINT-MARTIN (PARTIE NÉERLANDAISE)','SXM','SX');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (535,'BONAIRE, SAINT-EUSTACHE ET SABA','BES','BQ');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (540,'NOUVELLE-CALÉDONIE','NCL','NC');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (548,'VANUATU','VUT','VU');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (554,'NOUVELLE-ZÉLANDE','NZL','NZ');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (558,'NICARAGUA','NIC','NI');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (562,'NIGER','NER','NE');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (566,'NIGÉRIA','NGA','NG');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (570,'NIUÉ','NIU','NU');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (574,'NORFOLK, ÎLE','NFK','NF');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (578,'NORVÈGE','NOR','NO');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (580,'MARIANNES DU NORD, ÎLES','MNP','MP');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (581,'ÎLES MINEURES ÉLOIGNÉES DES ÉTATS-UNIS','UMI','UM');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (583,'MICRONÉSIE, ÉTATS FÉDÉRÉS DE','FSM','FM');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (584,'MARSHALL, ÎLES','MHL','MH');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (585,'PALAOS','PLW','PW');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (586,'PAKISTAN','PAK','PK');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (591,'PANAMA','PAN','PA');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (598,'PAPOUASIE-NOUVELLE-GUINÉE','PNG','PG');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (600,'PARAGUAY','PRY','PY');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (604,'PÉROU','PER','PE');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (608,'PHILIPPINES','PHL','PH');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (612,'PITCAIRN','PCN','PN');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (616,'POLOGNE','POL','PL');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (620,'PORTUGAL','PRT','PT');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (624,'GUINÉE-BISSAU','GNB','GW');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (626,'TIMOR-LESTE','TLS','TL');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (630,'PORTO RICO','PRI','PR');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (634,'QATAR','QAT','QA');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (638,'RÉUNION','REU','RE');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (642,'ROUMANIE','ROU','RO');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (643,'RUSSIE, FÉDÉRATION DE','RUS','RU');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (646,'RWANDA','RWA','RW');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (652,'SAINT-BARTHÉLEMY','BLM','BL');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (654,'SAINTE-HÉLÈNE, ASCENSION ET TRISTAN DA CUNHA','SHN','SH');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (659,'SAINT-KITTS-ET-NEVIS','KNA','KN');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (660,'ANGUILLA','AIA','AI');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (662,'SAINTE-LUCIE','LCA','LC');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (663,'SAINT-MARTIN (PARTIE FRANÇAISE)','MAF','MF');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (666,'SAINT-PIERRE-ET-MIQUELON','SPM','PM');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (670,'SAINT-VINCENT-ET-LES-GRENADINES','VCT','VC');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (674,'SAINT-MARIN','SMR','SM');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (678,'SAO TOMÉ-ET-PRINCIPE','STP','ST');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (682,'ARABIE SAOUDITE','SAU','SA');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (686,'SÉNÉGAL','SEN','SN');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (688,'SERBIE','SRB','RS');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (690,'SEYCHELLES','SYC','SC');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (694,'SIERRA LEONE','SLE','SL');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (702,'SINGAPOUR','SGP','SG');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (703,'SLOVAQUIE','SVK','SK');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (704,'VIET NAM','VNM','VN');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (705,'SLOVÉNIE','SVN','SI');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (706,'SOMALIE','SOM','SO');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (710,'AFRIQUE DU SUD','ZAF','ZA');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (716,'ZIMBABWE','ZWE','ZW');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (724,'ESPAGNE','ESP','ES');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (728,'SOUDAN DU SUD','SSD','SS');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (729,'SOUDAN','SDN','SD');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (732,'SAHARA OCCIDENTAL','ESH','EH');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (740,'SURINAME','SUR','SR');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (744,'SVALBARD ET ÎLE JAN MAYEN','SJM','SJ');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (748,'ESWATINI','SWZ','SZ');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (752,'SUÈDE','SWE','SE');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (756,'SUISSE','CHE','CH');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (760,'SYRIENNE, RÉPUBLIQUE ARABE','SYR','SY');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (762,'TADJIKISTAN','TJK','TJ');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (764,'THAÏLANDE','THA','TH');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (768,'TOGO','TGO','TG');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (772,'TOKELAU','TKL','TK');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (776,'TONGA','TON','TO');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (780,'TRINITÉ-ET-TOBAGO','TTO','TT');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (784,'ÉMIRATS ARABES UNIS','ARE','AE');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (788,'TUNISIE','TUN','TN');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (792,'TURQUIE','TUR','TR');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (795,'TURKMÉNISTAN','TKM','TM');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (796,'TURKS ET CAÏQUES, ÎLES','TCA','TC');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (798,'TUVALU','TUV','TV');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (800,'OUGANDA','UGA','UG');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (804,'UKRAINE','UKR','UA');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (807,'RÉPUBLIQUE DE MACÉDOINE','MKD','MK');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (818,'ÉGYPTE','EGY','EG');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (826,'ROYAUME-UNI','GBR','GB');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (831,'GUERNESEY','GGY','GG');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (832,'JERSEY','JEY','JE');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (833,'ÎLE DE MAN','IMN','IM');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (834,'TANZANIE, RÉPUBLIQUE UNIE DE','TZA','TZ');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (840,'ÉTATS-UNIS','USA','US');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (850,'ÎLES VIERGES DES ÉTATS-UNIS','VIR','VI');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (854,'BURKINA FASO','BFA','BF');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (858,'URUGUAY','URY','UY');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (860,'OUZBÉKISTAN','UZB','UZ');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (862,'VENEZUELA, RÉPUBLIQUE BOLIVARIENNE DU','VEN','VE');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (876,'WALLIS-ET-FUTUNA','WLF','WF');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (882,'SAMOA','WSM','WS');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (887,'YÉMEN','YEM','YE');
INSERT INTO PAYS (pays_code, nom, code_alpha_2, code_alpha_3) VALUES (894,'ZAMBIE','ZMB','ZM');