SELECT * FROM cotation;

INSERT INTO cotation (cotation, description)
VALUES ('1', 'Sentier à plat'),
('2', 'Sentier escarpé'),
('3','Début d''usage des mains, voies enfants'),
('4a','Initiation'),
('4b','Initiation'),
('4c','Initiation'),
('5a','Perfectionnement'),
('5b','Perfectionnement'),
('5c','Perfectionnement'),
('6a','Escalade technique, adhérence, petites prises'),
('6b','Escalade technique, adhérence, petites prises'),
('6c','Escalade technique, adhérence, petites prises'),
('7a','Escalade physique, parfois en dévers'),
('7b','Début en compétition'),
('7c','Début en compétition'),
('8a','Haut Niveau'),
('8b','Haut Niveau'),
('8c','Haut Niveau'),
('9a','Escalade extrême, Top niveau mondial'),
('9a+','Escalade extrême, Top niveau mondial'),
('9b','Escalade extrême, Top niveau mondial'),
('9b+','Le plus dur réalisé');